// GENERATED by design-system/tool/generate.py from design-system/tokens.json. Do not edit by hand.
// Source of truth: design-system/tokens.json · Spec: design-system/README.md
// Version 2.0.0

// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

/// The four 10-step ramps. The brand value of each ramp is marked.
abstract final class CharakPalette {
  // Blue — Primary · trust, every action (brand: 500)
  static const blue50 = Color(0xFFEEF3FD);
  static const blue100 = Color(0xFFD9E4FA);
  static const blue200 = Color(0xFFB3C8F4);
  static const blue300 = Color(0xFF84A5EC);
  static const blue400 = Color(0xFF4F7CDD);
  static const blue500 = Color(0xFF2456C9);
  static const blue600 = Color(0xFF1D45A6);
  static const blue700 = Color(0xFF183885);
  static const blue800 = Color(0xFF132B66);
  static const blue900 = Color(0xFF0D1D45);

  // Chandan — Brand warmth · from the logo (copper wordmark, gold halo) (brand: 500)
  static const chandan50 = Color(0xFFFDF8EF);
  static const chandan100 = Color(0xFFF7EAD4);
  static const chandan200 = Color(0xFFEDD2A6);
  static const chandan300 = Color(0xFFDDB06A);
  static const chandan400 = Color(0xFFC88442);
  static const chandan500 = Color(0xFFA85A26);
  static const chandan600 = Color(0xFF8E4B1F);
  static const chandan700 = Color(0xFF733C19);
  static const chandan800 = Color(0xFF572D13);
  static const chandan900 = Color(0xFF3B1E0C);

  // Sage — Health, success · the leaves (brand: 500)
  static const sage50 = Color(0xFFF3F4EC);
  static const sage100 = Color(0xFFE3E6D4);
  static const sage200 = Color(0xFFC8CDAE);
  static const sage300 = Color(0xFFA9B087);
  static const sage400 = Color(0xFF8A9266);
  static const sage500 = Color(0xFF6F774F);
  static const sage600 = Color(0xFF5C613F);
  static const sage700 = Color(0xFF4A4F33);
  static const sage800 = Color(0xFF373B27);
  static const sage900 = Color(0xFF25281A);

  // Ink — Text, chrome, doctor app (brand: 900)
  static const ink50 = Color(0xFFF4F5F7);
  static const ink100 = Color(0xFFE6E8EC);
  static const ink200 = Color(0xFFCDD1D8);
  static const ink300 = Color(0xFFA6ADB8);
  static const ink400 = Color(0xFF7A8494);
  static const ink500 = Color(0xFF566072);
  static const ink600 = Color(0xFF3C4556);
  static const ink700 = Color(0xFF283142);
  static const ink800 = Color(0xFF182031);
  static const ink900 = Color(0xFF0E1726);

  // Status solids — every booking state has exactly one colour.
  static const statusRequested = Color(0xFFC88442); // Requested
  static const statusAccepted = Color(0xFF2456C9); // Accepted
  static const statusConfirmed = Color(0xFF5E7F3A); // Paid · Confirmed
  static const statusActive = Color(0xFF6B4FC9); // Active visit
  static const statusReview = Color(0xFFE07A1F); // Needs review
  static const statusDeclined = Color(0xFFD23B3B); // Declined
}

/// One status colour set: [solid] for dots and icons, [soft] as a chip
/// fill with [on] as its label colour.
final class CharakStatusColors {
  final Color solid;
  final Color soft;
  final Color on;
  const CharakStatusColors({required this.solid, required this.soft, required this.on});
}

/// Semantic colour roles for one app surface. The patient app runs on
/// [CharakScheme.patient] (cream + white), the doctor app on
/// [CharakScheme.doctor] (ink). Screens read roles, never raw ramps.
final class CharakScheme {
  final Brightness brightness;
  final Color ground;
  final Color card;
  final Color tint;
  final Color warm;
  final Color fill;
  final Color text;
  final Color textMuted;
  final Color textFaint;
  final Color line;
  final Color lineStrong;
  final Color primary;
  final Color onPrimary;
  final Color primaryPressed;
  final Color primarySoft;
  final Color primaryMid;
  final Color onPrimarySoft;
  final Color accentWarm;
  final Color accentWarmSoft;
  final Color onAccentWarmSoft;
  final Color greeting;
  final Color success;
  final Color warning;
  final Color danger;
  final Color dangerSoft;
  final Color onDangerSoft;
  final Color chrome;
  final Color onChrome;
  final Color scrim;
  final CharakStatusColors requested;
  final CharakStatusColors accepted;
  final CharakStatusColors confirmed;
  final CharakStatusColors active;
  final CharakStatusColors review;
  final CharakStatusColors declined;
  final CharakStatusColors neutral;

  const CharakScheme({
    required this.brightness,
    required this.ground,
    required this.card,
    required this.tint,
    required this.warm,
    required this.fill,
    required this.text,
    required this.textMuted,
    required this.textFaint,
    required this.line,
    required this.lineStrong,
    required this.primary,
    required this.onPrimary,
    required this.primaryPressed,
    required this.primarySoft,
    required this.primaryMid,
    required this.onPrimarySoft,
    required this.accentWarm,
    required this.accentWarmSoft,
    required this.onAccentWarmSoft,
    required this.greeting,
    required this.success,
    required this.warning,
    required this.danger,
    required this.dangerSoft,
    required this.onDangerSoft,
    required this.chrome,
    required this.onChrome,
    required this.scrim,
    required this.requested,
    required this.accepted,
    required this.confirmed,
    required this.active,
    required this.review,
    required this.declined,
    required this.neutral,
  });

  static const patient = CharakScheme(
    brightness: Brightness.light,
    ground: Color(0xFFF7F3EC),
    card: Color(0xFFFFFFFF),
    tint: Color(0xFFEEF3FD),
    warm: Color(0xFFFDF8EF),
    fill: Color(0xFFF4F5F7),
    text: Color(0xFF0E1726),
    textMuted: Color(0xFF566072),
    textFaint: Color(0xFFA6ADB8),
    line: Color(0xFFE6E8EC),
    lineStrong: Color(0xFFCDD1D8),
    primary: Color(0xFF2456C9),
    onPrimary: Color(0xFFFFFFFF),
    primaryPressed: Color(0xFF1D45A6),
    primarySoft: Color(0xFFEEF3FD),
    primaryMid: Color(0xFFD9E4FA),
    onPrimarySoft: Color(0xFF183885),
    accentWarm: Color(0xFFA85A26),
    accentWarmSoft: Color(0xFFF7EAD4),
    onAccentWarmSoft: Color(0xFF733C19),
    greeting: Color(0xFF8E4B1F),
    success: Color(0xFF5E7F3A),
    warning: Color(0xFFE07A1F),
    danger: Color(0xFFD23B3B),
    dangerSoft: Color(0xFFFBE3E3),
    onDangerSoft: Color(0xFFA12A2A),
    chrome: Color(0xFF0E1726),
    onChrome: Color(0xFFFFFFFF),
    scrim: Color(0x730E1726),
    requested: CharakStatusColors(solid: Color(0xFFC88442), soft: Color(0xFFF7EAD4), on: Color(0xFF733C19)),
    accepted: CharakStatusColors(solid: Color(0xFF2456C9), soft: Color(0xFFD9E4FA), on: Color(0xFF183885)),
    confirmed: CharakStatusColors(solid: Color(0xFF5E7F3A), soft: Color(0xFFE6EEDC), on: Color(0xFF3F5A24)),
    active: CharakStatusColors(solid: Color(0xFF6B4FC9), soft: Color(0xFFECE7FA), on: Color(0xFF4A3499)),
    review: CharakStatusColors(solid: Color(0xFFE07A1F), soft: Color(0xFFFDEBD9), on: Color(0xFF9A4E0C)),
    declined: CharakStatusColors(solid: Color(0xFFD23B3B), soft: Color(0xFFFBE3E3), on: Color(0xFFA12A2A)),
    neutral: CharakStatusColors(solid: Color(0xFF566072), soft: Color(0xFFF4F5F7), on: Color(0xFF3C4556)),
  );

  static const doctor = CharakScheme(
    brightness: Brightness.dark,
    ground: Color(0xFF0E1726),
    card: Color(0xFF182031),
    tint: Color(0xFF132B66),
    warm: Color(0xFF3B1E0C),
    fill: Color(0xFF283142),
    text: Color(0xFFF4F5F7),
    textMuted: Color(0xFFA6ADB8),
    textFaint: Color(0xFF7A8494),
    line: Color(0xFF283142),
    lineStrong: Color(0xFF3C4556),
    primary: Color(0xFF2456C9),
    onPrimary: Color(0xFFFFFFFF),
    primaryPressed: Color(0xFF1D45A6),
    primarySoft: Color(0xFF132B66),
    primaryMid: Color(0xFF183885),
    onPrimarySoft: Color(0xFFB3C8F4),
    accentWarm: Color(0xFFDDB06A),
    accentWarmSoft: Color(0xFF3B1E0C),
    onAccentWarmSoft: Color(0xFFEDD2A6),
    greeting: Color(0xFFDDB06A),
    success: Color(0xFFA9B087),
    warning: Color(0xFFF0A35E),
    danger: Color(0xFFF07C7C),
    dangerSoft: Color(0xFF3A1F24),
    onDangerSoft: Color(0xFFF4A5A5),
    chrome: Color(0xFF0E1726),
    onChrome: Color(0xFFFFFFFF),
    scrim: Color(0x99000000),
    requested: CharakStatusColors(solid: Color(0xFFC88442), soft: Color(0xFF3B1E0C), on: Color(0xFFEDD2A6)),
    accepted: CharakStatusColors(solid: Color(0xFF2456C9), soft: Color(0xFF132B66), on: Color(0xFFB3C8F4)),
    confirmed: CharakStatusColors(solid: Color(0xFF5E7F3A), soft: Color(0xFF25281A), on: Color(0xFFC8CDAE)),
    active: CharakStatusColors(solid: Color(0xFF6B4FC9), soft: Color(0xFF2A2152), on: Color(0xFFCFC3F5)),
    review: CharakStatusColors(solid: Color(0xFFE07A1F), soft: Color(0xFF3D2410), on: Color(0xFFF6C08F)),
    declined: CharakStatusColors(solid: Color(0xFFD23B3B), soft: Color(0xFF3A1F24), on: Color(0xFFF4A5A5)),
    neutral: CharakStatusColors(solid: Color(0xFFA6ADB8), soft: Color(0xFF283142), on: Color(0xFFCDD1D8)),
  );

}

/// Specialty tile tones (bg, fg), keyed by category slug.
abstract final class CharakTileTones {
  static const general = (Color(0xFFEEF3FD), Color(0xFF183885));
  static const paediatrics = (Color(0xFFFDF8EF), Color(0xFF733C19));
  static const cardiology = (Color(0xFFFBEAEA), Color(0xFFA12A2A));
  static const ayurveda = (Color(0xFFE3E6D4), Color(0xFF4A4F33));
  static const skin = (Color(0xFFECE7FA), Color(0xFF4A3499));
  static const ortho = (Color(0xFFF4F5F7), Color(0xFF283142));
  static const all = [general, paediatrics, cardiology, ayurveda, skin, ortho];
}

/// The Anek type scale. Width (wdth) is the identity: wide headers, normal
/// reading text, narrow tabular numbers.
abstract final class CharakType {
  static const family = 'packages/charak_core/Anek';
  static const familyDevanagari = 'packages/charak_core/AnekDevanagari';
  static const fallback = [familyDevanagari];

  /// 56/60 · wght 750 · wdth 125
  static const display = TextStyle(
    fontFamily: family,
    fontFamilyFallback: fallback,
    fontSize: 56.0,
    height: 60 / 56,
    fontWeight: FontWeight.w700,
    fontVariations: [FontVariation('wdth', 125.0), FontVariation('wght', 750.0)],
  );
  /// 36/42 · wght 700 · wdth 122
  static const titleLarge = TextStyle(
    fontFamily: family,
    fontFamilyFallback: fallback,
    fontSize: 36.0,
    height: 42 / 36,
    fontWeight: FontWeight.w700,
    fontVariations: [FontVariation('wdth', 122.0)],
  );
  /// 26/32 · wght 650 · wdth 118
  static const titleMedium = TextStyle(
    fontFamily: family,
    fontFamilyFallback: fallback,
    fontSize: 26.0,
    height: 32 / 26,
    fontWeight: FontWeight.w600,
    fontVariations: [FontVariation('wdth', 118.0), FontVariation('wght', 650.0)],
  );
  /// 20/26 · wght 650 · wdth 112
  static const titleSmall = TextStyle(
    fontFamily: family,
    fontFamilyFallback: fallback,
    fontSize: 20.0,
    height: 26 / 20,
    fontWeight: FontWeight.w600,
    fontVariations: [FontVariation('wdth', 112.0), FontVariation('wght', 650.0)],
  );
  /// 18/26 · wght 400 · wdth 100
  static const bodyLarge = TextStyle(
    fontFamily: family,
    fontFamilyFallback: fallback,
    fontSize: 18.0,
    height: 26 / 18,
    fontWeight: FontWeight.w400,
    fontVariations: [FontVariation('wdth', 100.0)],
  );
  /// 16/24 · wght 400 · wdth 100
  static const body = TextStyle(
    fontFamily: family,
    fontFamilyFallback: fallback,
    fontSize: 16.0,
    height: 24 / 16,
    fontWeight: FontWeight.w400,
    fontVariations: [FontVariation('wdth', 100.0)],
  );
  /// 15/20 · wght 600 · wdth 105
  static const label = TextStyle(
    fontFamily: family,
    fontFamilyFallback: fallback,
    fontSize: 15.0,
    height: 20 / 15,
    fontWeight: FontWeight.w600,
    fontVariations: [FontVariation('wdth', 105.0)],
  );
  /// 13/18 · wght 500 · wdth 100
  static const caption = TextStyle(
    fontFamily: family,
    fontFamilyFallback: fallback,
    fontSize: 13.0,
    height: 18 / 13,
    fontWeight: FontWeight.w500,
    fontVariations: [FontVariation('wdth', 100.0)],
  );
  /// 12/16 · wght 700 · wdth 110 · UPPERCASE
  static const overline = TextStyle(
    fontFamily: family,
    fontFamilyFallback: fallback,
    fontSize: 12.0,
    height: 16 / 12,
    fontWeight: FontWeight.w700,
    fontVariations: [FontVariation('wdth', 110.0)],
    letterSpacing: 1.2,
  );
  /// 20/24 · wght 600 · wdth 80 · tabular
  static const numeric = TextStyle(
    fontFamily: family,
    fontFamilyFallback: fallback,
    fontSize: 20.0,
    height: 24 / 20,
    fontWeight: FontWeight.w600,
    fontVariations: [FontVariation('wdth', 80.0)],
    fontFeatures: [FontFeature.tabularFigures()],
  );
}

abstract final class CharakRadii {
  static const double pill = 999.0;
  static const double sheet = 32.0;
  static const double card = 26.0;
  static const double tile = 20.0;
  static const double field = 20.0;
  static const double avatar = 16.0;
}

abstract final class CharakSizes {
  static const double buttonMinHeight = 52.0;
  static const double buttonCompact = 44.0;
  static const double chipHeight = 40.0;
  static const double touchMin = 44.0;
  static const double bottomBarHeight = 68.0;
  static const double navPillWidth = 56.0;
  static const double navPillHeight = 32.0;
  static const double nowBarHeight = 60.0;
}

abstract final class CharakSpace {
  static const double xs = 4.0;
  static const double sm = 8.0;
  static const double md = 12.0;
  static const double base = 16.0;
  static const double gutter = 20.0;
  static const double lg = 24.0;
  static const double xl = 32.0;
  static const double xxl = 48.0;
}

/// Quick out, soft landing. Nothing runs longer than
/// 450ms; with Reduce motion on everything is a
/// 150ms fade.
abstract final class CharakMotion {
  static const double pressScale = 0.96;
  static const double liftOffset = 20.0;
  static const int staggerMaxItems = 6;
  static const double headerFadeStart = 170.0;
  static const double headerFadeEnd = 230.0;
  static const double headerParallax = 0.35;

  /// Buttons, tiles, rows · scale 0.96
  static const press = Duration(milliseconds: 150);
  static const pressCurve = Cubic(0.22, 1.0, 0.36, 1.0);
  /// Tabs, segments, status, colour
  static const standard = Duration(milliseconds: 300);
  static const standardCurve = Cubic(0.33, 0.0, 0.1, 1.0);
  /// Enter, Now Bar, sheets, card → screen
  static const emphasized = Duration(milliseconds: 450);
  static const emphasizedCurve = Cubic(0.22, 1.0, 0.36, 1.0);
  /// Dismiss, heads-up out, close
  static const exit = Duration(milliseconds: 200);
  static const exitCurve = Cubic(0.4, 0.0, 1.0, 1.0);
  /// Added per item on screen enter (240ms tail max)
  static const stagger = Duration(milliseconds: 40);
  /// Pulse on anything happening now (looping)
  static const live = Duration(milliseconds: 1600);
  /// Everything becomes a plain fade when Reduce motion is on
  static const reduced = Duration(milliseconds: 150);
}
