#!/usr/bin/env python3
"""Generate every platform's design tokens from design-system/tokens.json.

    python3 design-system/tool/generate.py          # write all outputs
    python3 design-system/tool/generate.py --check  # fail if any output is stale

Outputs (never edit these by hand, edit tokens.json and re-run):

  packages/charak_core/lib/design/tokens.g.dart   Flutter (patient + doctor apps)
  admin/src/styles/charak-tokens.css              Admin web (Tailwind reads the vars)
  opendesign/design-systems/charak/colors_and_type.css   HTML mockups / prototypes

Standard library only, so it runs anywhere Python 3.8+ does.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TOKENS = ROOT / "design-system" / "tokens.json"

DART_OUT = ROOT / "packages/charak_core/lib/design/tokens.g.dart"
ADMIN_CSS_OUT = ROOT / "admin/src/styles/charak-tokens.css"
OPENDESIGN_CSS_OUT = ROOT / "opendesign/design-systems/charak/colors_and_type.css"

HEADER = "GENERATED by design-system/tool/generate.py from design-system/tokens.json. Do not edit by hand."

STATUS_KEYS = ["requested", "accepted", "confirmed", "active", "review", "declined", "neutral"]
SCHEME_KEYS = [
    "ground", "card", "tint", "warm", "fill", "text", "textMuted", "textFaint", "line", "lineStrong",
    "primary", "onPrimary", "primaryPressed", "primarySoft", "primaryMid", "onPrimarySoft",
    "accentWarm", "accentWarmSoft", "onAccentWarmSoft", "greeting",
    "success", "warning", "danger", "dangerSoft", "onDangerSoft",
    "chrome", "onChrome", "scrim",
]
STEPS = ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900"]


# ── helpers ─────────────────────────────────────────────────────────────────

def argb(hex_: str) -> str:
    """'#RRGGBB' → 'Color(0xFFRRGGBB)'; '#AARRGGBB' → 'Color(0xAARRGGBB)'."""
    h = hex_.lstrip("#").upper()
    if len(h) == 6:
        h = "FF" + h
    if len(h) != 8:
        raise ValueError(f"bad colour {hex_!r}")
    return f"Color(0x{h})"


def css_hex(hex_: str) -> str:
    """CSS wants #RRGGBBAA, tokens.json stores 8-digit colours as #AARRGGBB."""
    h = hex_.lstrip("#").upper()
    return f"#{h[2:]}{h[:2]}" if len(h) == 8 else f"#{h}"


def rgb_channels(hex_: str) -> str:
    h = hex_.lstrip("#")[-6:]
    return " ".join(str(int(h[i:i + 2], 16)) for i in (0, 2, 4))


def kebab(name: str) -> str:
    out = ""
    for ch in name:
        out += ("-" + ch.lower()) if ch.isupper() else ch
    return out


def cubic(c) -> str:
    return f"Cubic({', '.join(repr(float(x)) for x in c)})"


def num(x) -> str:
    return repr(float(x))


def nearest_weight(w: int) -> int:
    """FontWeight only has 100 steps. Round down (650 → 600, 750 → 700); the
    exact value rides on the variable font's wght axis instead."""
    return max(100, min(900, w // 100 * 100))


# ── Dart ────────────────────────────────────────────────────────────────────

def dart(t: dict) -> str:
    c = t["color"]
    out: list[str] = []
    w = out.append
    w(f"// {HEADER}")
    w("// Source of truth: design-system/tokens.json · Spec: design-system/README.md")
    w(f"// Version {t['meta']['version']}")
    w("")
    w("// ignore_for_file: constant_identifier_names")
    w("")
    w("import 'package:flutter/widgets.dart';")
    w("")

    # Ramps
    w("/// The four 10-step ramps. The brand value of each ramp is marked.")
    w("abstract final class CharakPalette {")
    for ramp, spec in c["ramp"].items():
        w(f"  // {ramp[0].upper() + ramp[1:]} — {spec['role']} (brand: {spec['brand']})")
        for s in STEPS:
            w(f"  static const {ramp}{s} = {argb(spec[s])};")
        w("")
    w("  // Status solids — every booking state has exactly one colour.")
    for k, v in c["status"].items():
        w(f"  static const status{k[0].upper() + k[1:]} = {argb(v['solid'])}; // {v['label']}")
    w("}")
    w("")

    # Status pair
    w("/// One status colour set: [solid] for dots and icons, [soft] as a chip")
    w("/// fill with [on] as its label colour.")
    w("final class CharakStatusColors {")
    w("  final Color solid;")
    w("  final Color soft;")
    w("  final Color on;")
    w("  const CharakStatusColors({required this.solid, required this.soft, required this.on});")
    w("}")
    w("")

    # Scheme
    w("/// Semantic colour roles for one app surface. The patient app runs on")
    w("/// [CharakScheme.patient] (cream + white), the doctor app on")
    w("/// [CharakScheme.doctor] (ink). Screens read roles, never raw ramps.")
    w("final class CharakScheme {")
    w("  final Brightness brightness;")
    for k in SCHEME_KEYS:
        w(f"  final Color {k};")
    for k in STATUS_KEYS:
        w(f"  final CharakStatusColors {k};")
    w("")
    w("  const CharakScheme({")
    w("    required this.brightness,")
    for k in SCHEME_KEYS + STATUS_KEYS:
        w(f"    required this.{k},")
    w("  });")
    w("")
    neutral_solid = {"patient": c["ramp"]["ink"]["500"], "doctor": c["ramp"]["ink"]["300"]}
    for name, sch in c["scheme"].items():
        w(f"  static const {name} = CharakScheme(")
        w(f"    brightness: Brightness.{sch['brightness']},")
        for k in SCHEME_KEYS:
            w(f"    {k}: {argb(sch[k])},")
        for k in STATUS_KEYS:
            solid = c["status"][k]["solid"] if k in c["status"] else neutral_solid[name]
            st = sch["status"][k]
            w(f"    {k}: CharakStatusColors(solid: {argb(solid)}, soft: {argb(st['soft'])}, on: {argb(st['on'])}),")
        w("  );")
        w("")
    w("}")
    w("")

    # Tiles
    w("/// Specialty tile tones (bg, fg), keyed by category slug.")
    w("abstract final class CharakTileTones {")
    for k, v in c["tile"].items():
        w(f"  static const {k} = ({argb(v['bg'])}, {argb(v['fg'])});")
    w("  static const all = [" + ", ".join(c["tile"].keys()) + "];")
    w("}")
    w("")

    # Type
    ty = t["type"]
    w("/// The Anek type scale. Width (wdth) is the identity: wide headers, normal")
    w("/// reading text, narrow tabular numbers.")
    w("abstract final class CharakType {")
    w(f"  static const family = 'packages/charak_core/{ty['family']}';")
    w(f"  static const familyDevanagari = 'packages/charak_core/{ty['familyDevanagari']}';")
    w("  static const fallback = [familyDevanagari];")
    w("")
    for name, st in ty["style"].items():
        weight = st["weight"]
        fw = nearest_weight(weight)
        vars_ = [f"FontVariation('wdth', {num(st['width'])})"]
        if weight % 100:
            vars_.append(f"FontVariation('wght', {num(weight)})")
        extra = []
        if st.get("tracking"):
            extra.append(f"letterSpacing: {num(st['tracking'])}")
        if st.get("tabular"):
            extra.append("fontFeatures: [FontFeature.tabularFigures()]")
        w(f"  /// {st['size']}/{st['line']} · wght {weight} · wdth {st['width']}"
          + (" · UPPERCASE" if st.get("uppercase") else "")
          + (" · tabular" if st.get("tabular") else ""))
        w(f"  static const {name} = TextStyle(")
        w("    fontFamily: family,")
        w("    fontFamilyFallback: fallback,")
        w(f"    fontSize: {num(st['size'])},")
        w(f"    height: {st['line']} / {st['size']},")
        w(f"    fontWeight: FontWeight.w{fw},")
        w(f"    fontVariations: [{', '.join(vars_)}],")
        for e in extra:
            w(f"    {e},")
        w("  );")
    w("}")
    w("")

    # Radii / sizes / spacing
    w("abstract final class CharakRadii {")
    for k, v in t["radius"].items():
        w(f"  static const double {k} = {num(v)};")
    w("}")
    w("")
    w("abstract final class CharakSizes {")
    for k, v in t["size"].items():
        w(f"  static const double {k} = {num(v)};")
    w("}")
    w("")
    w("abstract final class CharakSpace {")
    for k, v in t["space"].items():
        w(f"  static const double {k} = {num(v)};")
    w("}")
    w("")

    # Motion
    m = t["motion"]
    w("/// Quick out, soft landing. Nothing runs longer than")
    w(f"/// {m['maxDuration']}ms; with Reduce motion on everything is a")
    w(f"/// {m['token']['reduced']['ms']}ms fade.")
    w("abstract final class CharakMotion {")
    w(f"  static const double pressScale = {num(m['pressScale'])};")
    w(f"  static const double liftOffset = {num(m['liftOffset'])};")
    w(f"  static const int staggerMaxItems = {m['token']['stagger']['maxItems']};")
    w(f"  static const double headerFadeStart = {num(m['header']['fadeStart'])};")
    w(f"  static const double headerFadeEnd = {num(m['header']['fadeEnd'])};")
    w(f"  static const double headerParallax = {num(m['header']['parallax'])};")
    w("")
    for k, v in m["token"].items():
        w(f"  /// {v['use']}")
        w(f"  static const {k} = Duration(milliseconds: {v['ms']});")
        if "curve" in v:
            w(f"  static const {k}Curve = {cubic(v['curve'])};")
    w("}")
    return "\n".join(out) + "\n"


# ── CSS ─────────────────────────────────────────────────────────────────────

def css_vars(t: dict, *, admin: bool) -> str:
    c = t["color"]
    lines: list[str] = []
    w = lines.append
    w(f"/* {HEADER}")
    w("   Source of truth: design-system/tokens.json · Spec: design-system/README.md */")
    w("")
    if not admin:
        w("@import url('https://fonts.googleapis.com/css2?family=Anek+Latin:wdth,wght@75..125,100..800&family=Anek+Devanagari:wdth,wght@75..125,100..800&display=swap');")
        w("")
    w(":root {")
    w("  /* ramps */")
    for ramp, spec in c["ramp"].items():
        for s in STEPS:
            w(f"  --{ramp}-{s}: {spec[s]};")
    w("")
    w("  /* status solids */")
    for k, v in c["status"].items():
        w(f"  --status-{k}: {v['solid']};")
    for scheme_name in ("patient", "doctor"):
        sch = c["scheme"][scheme_name]
        w("")
        w(f"  /* scheme: {scheme_name} ({sch['brightness']}) */")
        for k in SCHEME_KEYS:
            w(f"  --{scheme_name}-{kebab(k)}: {css_hex(sch[k])};")
        for k in STATUS_KEYS:
            w(f"  --{scheme_name}-status-{k}-soft: {sch['status'][k]['soft']};")
            w(f"  --{scheme_name}-status-{k}-on: {sch['status'][k]['on']};")
    w("")
    w("  /* type */")
    ty = t["type"]
    w("  --font-sans: 'Anek Latin', 'Anek Devanagari', system-ui, sans-serif;")
    for name, st in ty["style"].items():
        k = kebab(name)
        w(f"  --type-{k}: {st['weight']} {st['size']}px/{st['line']}px var(--font-sans);")
        w(f"  --type-{k}-width: {st['width']}%;")
    w("")
    w("  /* shape */")
    for k, v in t["radius"].items():
        w(f"  --radius-{kebab(k)}: {v}px;")
    for k, v in t["size"].items():
        w(f"  --size-{kebab(k)}: {v}px;")
    for k, v in t["space"].items():
        w(f"  --space-{kebab(k)}: {v}px;")
    w("")
    w("  /* motion */")
    m = t["motion"]
    for k, v in m["token"].items():
        w(f"  --dur-{k}: {v['ms']}ms;")
        if "curve" in v:
            w(f"  --ease-{k}: cubic-bezier({', '.join(str(x) for x in v['curve'])});")
    w(f"  --press-scale: {m['pressScale']};")
    if admin:
        # Admin runs the light (patient) scheme; Tailwind reads RGB channels
        # so `bg-primary/50` style alpha modifiers keep working.
        sch = c["scheme"]["patient"]
        w("")
        w("  /* Tailwind channels (admin uses the patient scheme) */")
        for k in SCHEME_KEYS:
            if len(sch[k].lstrip('#')) == 6:
                w(f"  --rgb-{kebab(k)}: {rgb_channels(sch[k])};")
        for ramp, spec in c["ramp"].items():
            for s in STEPS:
                w(f"  --rgb-{ramp}-{s}: {rgb_channels(spec[s])};")
    w("}")
    w("")
    w("/* Numbers: tabular + narrow, so fees and times line up. */")
    w(".tnum { font-variant-numeric: tabular-nums; font-stretch: 75%; }")
    w("/* Headers stay wide (never below 118) so the brand is recognisable. */")
    w(".display { font: var(--type-display); font-stretch: var(--type-display-width); }")
    for name in ("titleLarge", "titleMedium", "titleSmall"):
        k = kebab(name)
        w(f".{k} {{ font: var(--type-{k}); font-stretch: var(--type-{k}-width); }}")
    w("/* Press: scale 0.96, quick out and soft landing. */")
    w(".pressable { transition: transform var(--dur-press) var(--ease-press); }")
    w(".pressable:active { transform: scale(var(--press-scale)); }")
    w("@media (prefers-reduced-motion: reduce) {")
    w("  *, *::before, *::after { animation-duration: 150ms !important; animation-iteration-count: 1 !important; transition-duration: 150ms !important; }")
    w("  .pressable:active { transform: none; }")
    w("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    check = "--check" in sys.argv
    t = json.loads(TOKENS.read_text())
    outputs = {
        DART_OUT: dart(t),
        ADMIN_CSS_OUT: css_vars(t, admin=True),
        OPENDESIGN_CSS_OUT: css_vars(t, admin=False),
    }
    stale = []
    for path, text in outputs.items():
        rel = path.relative_to(ROOT)
        if check:
            if not path.exists() or path.read_text() != text:
                stale.append(str(rel))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        print(f"wrote {rel}")
    if stale:
        print("Stale generated token files (run design-system/tool/generate.py):")
        for s in stale:
            print(f"  {s}")
        return 1
    if check:
        print("Generated token files are up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
